/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bia.gui;

import bia.algorithms.IAlgorithm;
import bia.utils.Pair;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author pan0068
 */
public class AlgorithmPanel extends javax.swing.JPanel {

    
    private List<JComponent> fields;
    /**
     * Creates new form AlgorithmPanel
     */
    public AlgorithmPanel() {
        initComponents();
        this.fields = new ArrayList<>();
        this.setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS));
    }
    
    public void setAlgorithm(IAlgorithm alg)
    {
        for (JComponent c : fields)
        {
            c.setVisible(false);
            this.remove(c);
        }
        
        fields.clear();
        
        for (Pair<String, String> p : alg.getParameters())
        {
            JLabel lbl = new JLabel(p.first);
            JTextField field = new JTextField(p.second);
            
            this.add(lbl);
            this.add(field);
            
            this.fields.add(lbl);
            this.fields.add(field);
        }
    }
    
    public List<Float> values()
    {
        List<Float> ret = new ArrayList<>();
        
        for (JComponent c : this.fields)
        {
            if (c instanceof JTextField)
            {
                JTextField f = (JTextField)c;
                ret.add(Float.valueOf(f.getText()));
            }
        }
        
        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
